//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.14 at 03:08:57 AM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://article.nure.ua/entity/article/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ua.nure.article.entity.article;
