//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.14 at 02:28:59 AM EET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://article.nure.ua/entity/")
package ua.nure.article.entity;
